services:
  app:
    build: .
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_LOCATION=${GCP_LOCATION:-us-central1}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - PORT=${PORT:-8501}
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped
